const stores = [
    {
        //Fairmount
        address: {
            address1: "3325 West Genesee Street",
            address2: null,
            address3: null,
            city: "Syracuse",
            country: "USA",
            postal_code: "13219",
            province: "NY",
        },
        amenities:
            "Coin Counting Kiosk, Lottery, MoneyGram Bill Pay, RedBox, Wi-Fi Internet Access",
        associated_stores: [],
        banner: "Fairmount",
        ebt_enabled_in_state: false,
        ext_id: "11231",
        external_url: "https://www.wegmans.com/stores/fairmount-ny",
        has_catering: null,
        has_delivery: true,
        has_ecommerce: true,
        has_pickup: true,
        href: "/stores/65",
        id: "65",
        is_b2b: false,
        last_purchased: null,
        location: {
            latitude: "43.04694",
            longitude: "-76.22706",
        },
        name: "Fairmount",
        partial: null,
        payment_types: {
            delivery: ["auth_capture"],
            pickup: ["auth_capture"],
        },
        phone_number: "315-487-1581",
        retailer_store_id: "39",
        show_catering: null,
        show_delivery: true,
        show_ecommerce: true,
        show_pickup: true,
        store_banner: {
            ext_id: "231",
            key: "wegmans",
            name: "Wegmans",
        },
        store_hours: null,
        tipping_catering: false,
        tipping_delivery: true,
        tipping_pickup: false,
    },
    {
        // Jammes Street
        address: {
            address1: "4256 James Street",
            address2: null,
            address3: null,
            city: "East Syracuse",
            country: "USA",
            postal_code: "13057",
            province: "NY",
        },
        amenities:
            "Coin Counting Kiosk, Lottery, RedBox, Wi-Fi Internet Access",
        associated_stores: [],
        banner: "James St.",
        ebt_enabled_in_state: false,
        ext_id: "11214",
        external_url: "https://www.wegmans.com/stores/james-st-ny",
        has_catering: null,
        has_delivery: true,
        has_ecommerce: true,
        has_pickup: true,
        href: "/stores/12",
        id: "12",
        is_b2b: false,
        last_purchased: null,
        location: {
            latitude: "43.06882",
            longitude: "-76.08731",
        },
        name: "James St.",
        partial: null,
        payment_types: {
            delivery: ["auth_capture"],
            pickup: ["auth_capture"],
        },
        phone_number: "315-437-1534",
        retailer_store_id: "37",
        show_catering: null,
        show_delivery: true,
        show_ecommerce: true,
        show_pickup: true,
        store_banner: {
            ext_id: "231",
            key: "wegmans",
            name: "Wegmans",
        },
        store_hours: null,
        tipping_catering: false,
        tipping_delivery: true,
        tipping_pickup: false,
    },
    {
        // Onondaga
        address: {
            address1: "4722 Onondaga Boulevard",
            address2: null,
            address3: null,
            city: "Syracuse",
            country: "USA",
            postal_code: "13219",
            province: "NY",
        },
        amenities:
            "Coin Counting Kiosk, Lottery, MoneyGram Bill Pay, RedBox, Wi-Fi Internet Access",
        associated_stores: [],
        banner: "Onondaga",
        ebt_enabled_in_state: false,
        ext_id: "11228",
        external_url: "https://www.wegmans.com/stores/onondaga-ny",
        has_catering: null,
        has_delivery: true,
        has_ecommerce: true,
        has_pickup: true,
        href: "/stores/25",
        id: "25",
        is_b2b: false,
        last_purchased: null,
        location: {
            latitude: "43.03129",
            longitude: "-76.19117",
        },
        name: "Onondaga",
        partial: null,
        payment_types: {
            delivery: ["auth_capture"],
            pickup: ["auth_capture"],
        },
        phone_number: "315-478-3313",
        retailer_store_id: "31",
        show_catering: null,
        show_delivery: true,
        show_ecommerce: true,
        show_pickup: true,
        store_banner: {
            ext_id: "231",
            key: "wegmans",
            name: "Wegmans",
        },
        store_hours: null,
        tipping_catering: false,
        tipping_delivery: true,
        tipping_pickup: false,
    },
    { // John Glenn
        address: {
            address1: "7519 Oswego Road",
            address2: null,
            address3: null,
            city: "Liverpool",
            country: "USA",
            postal_code: "13090",
            province: "NY",
        },
        amenities:
            "Coin Counting Kiosk, Lottery, MoneyGram Bill Pay, RedBox, Wi-Fi Internet Access",
        associated_stores: [],
        banner: "John Glenn",
        ebt_enabled_in_state: false,
        ext_id: "11223",
        external_url: "https://www.wegmans.com/stores/john-glenn-ny",
        has_catering: null,
        has_delivery: true,
        has_ecommerce: true,
        has_pickup: true,
        href: "/stores/4",
        id: "4",
        is_b2b: false,
        last_purchased: null,
        location: {
            latitude: "43.13421",
            longitude: "-76.22546",
        },
        name: "John Glenn",
        partial: null,
        payment_types: {
            delivery: ["auth_capture"],
            pickup: ["auth_capture"],
        },
        phone_number: "315-546-1200",
        retailer_store_id: "1",
        show_catering: null,
        show_delivery: true,
        show_ecommerce: true,
        show_pickup: true,
        store_banner: {
            ext_id: "231",
            key: "wegmans",
            name: "Wegmans",
        },
        store_hours: null,
        tipping_catering: false,
        tipping_delivery: true,
        tipping_pickup: false,
    },
    {
        // Great Nothern
        address: {
            address1: "3955 Route 31",
            address2: null,
            address3: null,
            city: "Liverpool",
            country: "USA",
            postal_code: "13090",
            province: "NY",
        },
        amenities:
            "Coin Counting Kiosk, Lottery, MoneyGram Bill Pay, RedBox, Wi-Fi Internet Access",
        associated_stores: [],
        banner: "Great Northern",
        ebt_enabled_in_state: false,
        ext_id: "11225",
        external_url: "https://www.wegmans.com/stores/great-northern-ny",
        has_catering: null,
        has_delivery: true,
        has_ecommerce: true,
        has_pickup: true,
        href: "/stores/57",
        id: "57",
        is_b2b: false,
        last_purchased: null,
        location: {
            latitude: "43.18547",
            longitude: "-76.23781",
        },
        name: "Great Northern",
        partial: null,
        payment_types: {
            delivery: ["auth_capture"],
            pickup: ["auth_capture"],
        },
        phone_number: "315-622-4632",
        retailer_store_id: "35",
        show_catering: null,
        show_delivery: true,
        show_ecommerce: true,
        show_pickup: true,
        store_banner: {
            ext_id: "231",
            key: "wegmans",
            name: "Wegmans",
        },
        store_hours: null,
        tipping_catering: false,
        tipping_delivery: true,
        tipping_pickup: false,
    },
    { // Dewitt
        "address": {
        "address1": "6789 East Genesee Street",
        "address2": null,
        "address3": null,
        "city": "Fayetteville",
        "country": "USA",
        "postal_code": "13066",
        "province": "NY"
        },
        "amenities": "Coin Counting Kiosk, Lottery, MoneyGram Bill Pay, RedBox, Wi-Fi Internet Access",
        "associated_stores": [],
        "banner": "Dewitt",
        "ebt_enabled_in_state": false,
        "ext_id": "11217",
        "external_url": "https://www.wegmans.com/stores/dewitt-ny",
        "has_catering": null,
        "has_delivery": true,
        "has_ecommerce": true,
        "has_pickup": true,
        "href": "/stores/18",
        "id": "18",
        "is_b2b": false,
        "last_purchased": null,
        "location": {
        "latitude": "43.03141",
        "longitude": "-76.05250"
        },
        "name": "Dewitt",
        "partial": null,
        "payment_types": {
        "delivery": [
        "auth_capture"
        ],
        "pickup": [
        "auth_capture"
        ]
        },
        "phone_number": "315-446-1180",
        "retailer_store_id": "30",
        "show_catering": null,
        "show_delivery": true,
        "show_ecommerce": true,
        "show_pickup": true,
        "store_banner": {
        "ext_id": "231",
        "key": "wegmans",
        "name": "Wegmans"
        },
        "store_hours": null,
        "tipping_catering": false,
        "tipping_delivery": true,
        "tipping_pickup": false
        },
    {
        // Taft Road
        address: {
            address1: "4979 West Taft Road",
            address2: null,
            address3: null,
            city: "Liverpool",
            country: "USA",
            postal_code: "13088",
            province: "NY",
        },
        amenities:
            "Coin Counting Kiosk, Lottery, MoneyGram Bill Pay, RedBox, Wi-Fi Internet Access",
        associated_stores: [],
        banner: "Taft Rd.",
        ebt_enabled_in_state: false,
        ext_id: "11221",
        external_url: "https://www.wegmans.com/stores/taft-rd-ny",
        has_catering: null,
        has_delivery: true,
        has_ecommerce: true,
        has_pickup: true,
        href: "/stores/16",
        id: "16",
        is_b2b: false,
        last_purchased: null,
        location: {
            latitude: "43.12268",
            longitude: "-76.16908",
        },
        name: "Taft Rd.",
        partial: null,
        payment_types: {
            delivery: ["auth_capture"],
            pickup: ["auth_capture"],
        },
        phone_number: "315-457-0514",
        retailer_store_id: "34",
        show_catering: null,
        show_delivery: true,
        show_ecommerce: true,
        show_pickup: true,
        store_banner: {
            ext_id: "231",
            key: "wegmans",
            name: "Wegmans",
        },
        store_hours: null,
        tipping_catering: false,
        tipping_delivery: true,
        tipping_pickup: false,
    },
];

module.exports = stores;